---
- hosts: all
  become: yes

  vars:
    rh_org_id: 1268969
    rh_act_key: djoo-test


  tasks:
    - name: AWS rhui client
      dnf:
        name: rh-amazon-rhui-client*
        state: absent

    - name: Remove existing RHUI repo files
      file:
        path: /etc/yum.repos.d/*
        state: absent

    - name: subscription-manager configuration changes to enable repo managemnet
      command: /usr/bin/subscription-manager config --rhsm.manage_repos=1

    - name: Register the system to access.redhat.com
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ rh_act_key }}"
        org_id: "{{ rh_org_id }}"
        pool_ids:
          # Old pool ID 
          #- 8a85f9a17c5b1f49017c5b4c45fe121d
          #- 8a85f9a17c5b1f49017c5b4d952918ce
          - 2c94c08e8409945a01840db8b78f539d
          - 2c94c08e8409945a01840db8b645539b

    - name: To enable all repositories are disabled
      community.general.rhsm_repository:
        name: '*'
        state: disabled

    - name: To enable only required repositories
      community.general.rhsm_repository:
        name:
          - rhel-8-for-x86_64-appstream-rpms
          - rhel-8-for-x86_64-baseos-rpms
          - ansible-automation-platform-2.1-for-rhel-8-x86_64-rpms
        state: enabled

    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: install redhat cloud connector package
      dnf:
        name: 'rhc'
        state: latest

    - name: RHC registration
      command: rhc connect -a "{{ rh_act_key }}" -o "{{ rh_org_id }}"
